// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    // ✅ Unified environment variables (works in Cloudflare + local)
    const SUPABASE_URL =
      process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL

    const SUPABASE_ANON_KEY =
      process.env.SUPABASE_ANON_KEY ||
      process.env.VITE_SUPABASE_ANON_KEY ||
      process.env.SUPABASE_PUBLISHABLE_KEY

    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_ANON_KEY ? ['SUPABASE_ANON_KEY'] : []),
      ]

      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Cloudflare Variables.`

      console.error(`[Supabase] ${message}`)
      throw new Error(message)
    }

    const request = getRequest()

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available')
    }

    const authHeader = request.headers.get('authorization')

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided')
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported')
    }

    const token = authHeader.replace('Bearer ', '')

    if (!token) {
      throw new Error('Unauthorized: No token provided')
    }

    // ✅ Supabase client (server-side safe)
    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    })

    // ✅ Validate token
    const { data, error } = await supabase.auth.getUser(token)

    if (error || !data?.user) {
      throw new Error('Unauthorized: Invalid token')
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        user: data.user,
      },
    })
  }
)